const cvAndreu = ref([
    {
        id: 0,
        diseñador: "Antes",
        año: "2001",
        añoMin: "|",
        hasta: "2001",
        duracion: "2 meses",
        cargo: "Aprendiz de mécanico de compresores de aire",
        empresa: "DICELMAC AUTOMATISMES S.L.",
        descripcion: "Fue mi primer trabajo. Uno de esos trabajos de verano, durante las vacaciones del curso, donde aprovechas el tiempo para ganas tu primer salario. Mi función en la empresa fue limpiar piezas y servir herramientas al mecánico que montaba los compresores",
        formacion: "ESO - Estudios Secundarios Obligatorios",
        centro: "IES El Suí",
        curso: "1996-1999",
        nota: "6,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "",
            sSkDesc02: "",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "",
            hSkTools01: "",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }]
    },
    {
        id: 1,
        diseñador: "Antes",
        año: "2002",
        añoMin: "|",
        hasta: "2002",
        duracion: "2 meses",
        cargo: "Operario en rebobinadora de papel de celulosa",
        empresa: "CRISWEN, S.A.",
        descripcion: "Mi función en la empresa era cargar la máquina de papel, rebobinar el papel y extraer el producto para su empaquetado",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Photoshop, Macromedia Flash y Macromedia Freehand",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }]
    },
    {
        id: 2,
        diseñador: "Antes",
        año: "2003",
        añoMin: "|",
        hasta: "2003",
        duracion: "2 meses",
        cargo: "Operario de carretilla",
        empresa: "ALMACENES DIA%",
        descripcion: "Estuve en el equipo de descarga de camiones con carretilla elevadora",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Photoshop, Macromedia Flash y Macromedia Freehand",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],

    },
    {
        id: 3,
        diseñador: "Antes",
        año: "2004",
        añoMin: "|",
        hasta: "2005",
        duracion: "1 año",
        cargo: "Responsable de almacén y logística de equipos de montadores",
        empresa: "MOBLES PANORAMA S.A.",
        descripcion: "Al finalizar mis estudios en la Escuela Municipal de Arte y Diseño (Escola Municipal d'Art i Diseny de la Garriga (EMAD)) de La Garriga, estuve trabajando un año para poder sacarme el carnet B y poder seguir estudiando. Ese trabajo, a parte de darme libertad económica, me hizo crecer como trabajador. Por primera vez, por necesidad y casualidad, fui el responsable de sección de una empresa. Recepcionaba el producto de los proveedores, lo almacenaba por clientes minimizando el poco espacio que había y organizaba los grupos de trabajo y sus rutas de clientes.",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Photoshop, Macromedia Flash y Macromedia Freehand",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],

    },
    {
        id: 4,
        diseñador: "Antes",
        año: "2005",
        añoMin: "|",
        hasta: "2008",
        duracion: "2 años",
        cargo: "Responsable de almacén",
        empresa: "SAURMIDECOR S.A.",
        descripcion: "Por razones familiares, mis estudios se vieron afectados y tuve que volver al mundo laboral. Por suerte había tenido una buena experiencia en la última empresa y los compañeros me recomendaron en una empresa más grande, también en el sector de la logística y mobiliario. Mi cargo consistía en la organización del equipo de almacén, inventario y distribución de reparto a los transportistas",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 5,
        diseñador: "Antes",
        año: "2006",
        añoMin: "|",
        hasta: "2008",
        duracion: "2 años",
        cargo: "Responsable de almacén",
        empresa: "SAURMIDECOR S.A.",
        descripcion: "Por razones familiares, mis estudios se vieron afectados y tuve que volver al mundo laboral. Por suerte había tenido una buena experiencia en la última empresa y los compañeros me recomendaron en una empresa más grande, también en el sector de la logística y mobiliario. Mi cargo consistía en la organización del equipo de almacén, inventario y distribución de reparto a los transportistas",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 6,
        diseñador: "Antes",
        año: "2007",
        añoMin: "|",
        hasta: "2008",
        duracion: "2 años",
        cargo: "Responsable de almacén",
        empresa: "SAURMIDECOR S.A.",
        descripcion: "Por razones familiares, mis estudios se vieron afectados y tuve que volver al mundo laboral. Por suerte había tenido una buena experiencia en la última empresa y los compañeros me recomendaron en una empresa más grande, también en el sector de la logística y mobiliario. Mi cargo consistía en la organización del equipo de almacén, inventario y distribución de reparto a los transportistas",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "",
            sSkDesc03: "",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "",
            hSkTools02: "",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 7,
        diseñador: "Antes",
        año: "2008",
        añoMin: "|",
        hasta: "2008",
        duracion: "2 años",
        cargo: "Responsable de almacén",
        empresa: "SAURMIDECOR S.A.",
        descripcion: "Por razones familiares, mis estudios se vieron afectados y tuve que volver al mundo laboral. Por suerte había tenido una buena experiencia en la última empresa y los compañeros me recomendaron en una empresa más grande, también en el sector de la logística y mobiliario. Mi cargo consistía en la organización del equipo de almacén, inventario y distribución de reparto a los transportistas",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "",
            sSkDesc04: "",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],

    },
    {
        id: 8,
        diseñador: "Antes",
        año: "2009",
        añoMin: "|",
        hasta: "2010",
        duracion: "2 temporadas de 6 meses",
        cargo: "Cocinero",
        empresa: "CAFÈ EL PILAR",
        descripcion: "A raíz de la crisis económica de 2008, estuve en el paro y aproveché para estudiar un curso de Macromedia. Una vez acabado el curso me fui a buscar trabajo de temporada a las islas Baleares. Allí encontré un trabajo de cocinero, algo que a nivel laboral, nunca había hecho. Es cierto que como hobby si había hecho mis cosas en mi cocina, pero en aquel trabajo estuve solo ante el peligro. Diseñar menú, preparación y logística de los productos y cocinar en servicios de mañana y tarde-noche",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "",
            sSkDesc05: "",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 9,
        diseñador: "Antes",
        año: "2010",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 10,
        diseñador: "Antes",
        año: "2011",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 11,
        diseñador: "Antes",
        año: "2012",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 12,
        diseñador: "Antes",
        año: "2013",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 13,
        diseñador: "Antes",
        año: "2014",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "",
            hSkTools03: "",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 14,
        diseñador: "Antes",
        año: "2015",
        añoMin: "|",
        hasta: "2015",
        duracion: "5 años",
        cargo: "Oficial de primera en cartonaje para alimentación",
        empresa: "MEDIOAMBIENTE PACK S.A.",
        descripcion: "Un familiar me recomendó para entrar en esta empresa de Valencia. Nada más llegar sustituí a la persona que se encargaba de la impresora. Poco a poco fui conociendo toda la maquinaria de la empresa y llegué a llevar equipos de trabajo en las onduladoras de papel. Una de mis tareas era estandarizar los diferentes procesos de producción de cuatro de las siete máquinas que había en aquella empresa",
        formacion: "CFGM - Arte final en diseño gráfico",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2002-2004",
        nota: "7,6",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 15,
        diseñador: "Después",
        año: "2016",
        añoMin: "|",
        hasta: "2018",
        duracion: "2 años",
        cargo: "Diseñador gráfico",
        empresa: "VIENTO NORTE SUR",
        descripcion: "Fue mi primer trabajo como diseñador gráfico. La organización Viento Norte Sur, que se dedica a la coordinación de viajes solidarios por todo el mundo, me propuso rediseñar su branding y la UX de la web. Estuve trabajando con ellos mientras cursaba el Grado superior en Gráfica Interactiva",
        formacion: "CFGS - Gráfica Interactiva",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2016-2018",
        nota: "7,9",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía y fotografía",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "",
            hSkTools04: "",
        }],
    },
    {
        id: 16,
        diseñador: "Después",
        año: "2017",
        añoMin: "|",
        hasta: "2018",
        duracion: "2 años",
        cargo: "Diseñador gráfico",
        empresa: "VIENTO NORTE SUR",
        descripcion: "Fue mi primer trabajo como diseñador gráfico. La organización Viento Norte Sur, que se dedica a la coordinación de viajes solidarios por todo el mundo, me propuso rediseñar su branding y la UX de la web. Estuve trabajando con ellos mientras cursaba el Grado superior en Gráfica Interactiva",
        formacion: "CFGS - Gráfica Interactiva",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2016-2018",
        nota: "7,9",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 17,
        diseñador: "Después",
        año: "2018",
        añoMin: "|",
        hasta: "2019",
        duracion: "1 año",
        cargo: "Diseñador gráfico",
        empresa: "SIMBÒLIC COMUNICACIÓ",
        descripcion: "Después de cursar el primer Ciclo Formativo de Grado Superior en diseño, tuve la suerte de quedarme en la empresa donde hice las prácticas. Allí me encargaría del branding de algunos clientes. Diseño y rediseño de logotipos, maquetación editorial y algún que otro trabajo audiovisual. Estuve trabajando con ellos mientras cursaba mi segundo curso de Grado Superior en Gráfica Publicitaria",
        formacion: "CFGS - Gráfica Publicitaria",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2017-2018",
        nota: "8,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 18,
        diseñador: "Después",
        año: "2019",
        añoMin: "|",
        hasta: "2020",
        duracion: "1 año",
        cargo: "Diseñador gráfico",
        empresa: "PHOENIX TEEFACTORY S.L.",
        descripcion: "Una vez acabada mi formación como diseñador gráfico, me contrató una empresa de serigrafía y estampación de camisetas en el departamento de diseño gráfico. Allí haría tratamiento de imagenes, preparación de archivos para fotolitos y soporte en laboratorio de insolación",
        formacion: "CFGS - Gráfica Publicitaria",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2017-2018",
        nota: "8,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 19,
        diseñador: "Después",
        año: "2020",
        añoMin: "|",
        hasta: "2022",
        duracion: "2 años",
        cargo: "Diseñador gráfico y soporte en taller de serigrafía",
        empresa: "GLOBAL MANAGING S.L.U.",
        descripcion: "La oleada pandémica dejó a las empresas tocadas. Por suerte me contrataron en Global Managing para llevar el proyecto de ecommerce. Hasta que no empezó el proyecto, estuve encargandome del taller de entelaje",
        formacion: "CFGS - Gráfica Publicitaria",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2017-2018",
        nota: "8,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 20,
        diseñador: "Después",
        año: "2021",
        añoMin: "|",
        hasta: "2022",
        duracion: "2 años",
        cargo: "Diseñador gráfico y soporte en taller de serigrafía",
        empresa: "GLOBAL MANAGING S.L.U.",
        descripcion: "La oleada pandémica dejó a las empresas tocadas. Por suerte me contrataron en Global Managing para llevar el proyecto de ecommerce. Hasta que no empezó el proyecto, estuve encargandome del taller de entelaje",
        formacion: "CFGS - Gráfica Publicitaria",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2017-2018",
        nota: "8,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 21,
        diseñador: "Después",
        año: "2022",
        añoMin: "|",
        hasta: "2022",
        duracion: "2 años",
        cargo: "Diseñador gráfico y soporte en taller de serigrafía",
        empresa: "GLOBAL MANAGING S.L.U.",
        descripcion: "La oleada pandémica dejó a las empresas tocadas. Por suerte me contrataron en Global Managing para llevar el proyecto de ecommerce. Hasta que no empezó el proyecto, estuve encargandome del taller de entelaje",
        formacion: "CFGS - Gráfica Publicitaria",
        centro: "Escola Municipal d'Art i Diseny de la Garriga (EMAD)",
        curso: "2017-2018",
        nota: "8,4",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3",
        }],
    },
    {
        id: 22,
        diseñador: "Después",
        año: "2023",
        añoMin: "|",
        hasta: "hoy",
        duracion: "Trabajando",
        cargo: "Diseñador gráfico Frontend",
        empresa: "Autónomo",
        descripcion: "He decidio, después de toda mi trayectoria y con los conocimientos que tengo, especializarme en diseñador gráfico Front end. Creo que puedo aportar muchos valores a un equipo de diseño dentro de una empresa tecnológica. Actualmente estoy realizando pequeños proyectos reales como autónomo, aunque mi intención es trabajar para un equipo",
        formacion: "Curso de especialización - Frontend web developer",
        centro: "Universitat Autónoma de Barcelona",
        curso: "2022-2023",
        nota: "7",
        softSkills: [{
            sSkills01: "Aprendizaje activo",
            sSkDesc01: "Nuevas tecnologias, nuevos tiempos. Se que un continuo aprendizaje me va a acompañar a lo largo de mi trayectoria. Por eso se que acomodarse no es una opción",
            sSkills02: "Analsis y resolución de problemas",
            sSkDesc02: "La revolución constante de la tecnología nos obliga a tener herramientas para saber gestionar los cambios",
            sSkills03: "Flexibilidd y resiliencia",
            sSkDesc03: "Ser conocedorde las limitaciones y los problemas con el timing me lleva a ser, no solo resolutivo, sino a adaptar la solución al entorno de trabajo",
            sSkills04: "Gestión del cambo",
            sSkDesc04: "El cambio es algo cnstante en todos los escenarios de la vida. El cambio es positivo. El cambio nos hace crecer",
            sSkills05: "Inteligencia emocionaly empatía",
            sSkDesc05: "A lo largo de mi vida labral y personal he aprendido que el trabajo en equipo es esencial para lograr ejecutar cualquier proyecto",
        }],
        hardSkills: [{
            hSkills01: "Diseño gráfico",
            hSkTools01: "Adobe Creative Suite, ilustración, tipografía, fotografía y audiovisuales",
            hSkills02: "Logística",
            hSkTools02: "El orden y la indexación de productos, estocaje y gestión del equipo",
            hSkills03: "Estandarizar procesos de producción",
            hSkTools03: "Optimizar y contabilizar en timings los procesos para rentabilizar los proyectos",
            hSkills04: "Diseño gráfico Front end",
            hSkTools04: "Wordpess, UX, html5, css3, Javascript(Vue3), Figma",

        }],
    }
])